from flask import Flask, jsonify, request

app = Flask(__name__)
articles = [
    {
        "id": 1,
        "judul": "What is Cataract",
        "deskripsi": "Cataracts are a prevalent age-related eye condition that affects millions of individuals worldwide. The term cataracts refers to the clouding of the eye's natural lens, resulting in blurred vision and reduced visual acuity. The lens, responsible for focusing light onto the retina, gradually becomes opaque over time. This clouding obstructs the passage of light, leading to vision impairment and distortion. Cataracts typically develop slowly and progress over time. As the lens becomes cloudier, vision becomes increasingly blurry, making it challenging to read, drive, or perform daily tasks. Colors may appear dull or faded, and individuals may experience increased sensitivity to light and glare. Additionally, cataracts can cause difficulties with night vision, making it challenging to navigate in dimly lit environments. The primary cause of cataracts is age-related changes in the lens. However, other factors can contribute to their development. Prolonged exposure to ultraviolet (UV) radiation from the sun, diabetes, smoking, and excessive alcohol consumption are known risk factors for cataract formation. Certain medications, eye injuries, and certain medical conditions, such as obesity, may also increase the likelihood of developing cataracts. Fortunately, cataracts can be treated effectively through surgical intervention. Cataract surgery involves removing the clouded lens and replacing it with an artificial intraocular lens (IOL). This procedure is safe, commonly performed, and has a high success rate. Before undergoing cataract surgery, a comprehensive preoperative evaluation is conducted to determine the suitability of the procedure and select the most appropriate IOL. In conclusion, cataracts are a common eye condition characterized by the clouding of the natural lens. They cause blurred vision, color distortion, sensitivity to light, and difficulties with night vision. While age is the primary factor contributing to cataracts, other factors such as UV radiation, diabetes, smoking, and alcohol consumption can also play a role. Cataract surgery is an effective treatment option that can restore clear vision and improve the quality of life for individuals affected by cataracts.",
        "image_url": "https://storage.googleapis.com/image_articles/What%20is%20cataract.jpg"
    },
    {
        "id": 2,
        "judul": "Cataract Symptoms",
        "deskripsi": "Recognizing the symptoms of cataracts is crucial for early detection and timely treatment. Common symptoms include blurred vision, sensitivity to light, color distortion, and difficulty with night vision. By being aware of these signs, individuals can seek professional assistance and receive appropriate care. Blurred vision is one of the primary symptoms of cataracts. Individuals with cataracts may experience progressively blurry vision, making it difficult to see fine details or read small text. As the lens becomes cloudier, objects may appear hazy or out of focus. Sensitivity to light is another symptom associated with cataracts. Individuals may find that bright lights, such as sunlight or glare from artificial light sources, cause discomfort or glare. This sensitivity can interfere with daily activities and make it challenging to be in well-lit environments. Color distortion is a common symptom of cataracts. As the lens becomes clouded, colors may appear faded or yellowish. This can affect the perception of color intensity and make it challenging to distinguish between shades. Difficulty with night vision is a significant symptom of cataracts. In dim or low-light conditions, individuals with cataracts may experience decreased visual clarity and increased difficulty seeing in the dark. This can make driving at night or navigating in poorly lit areas challenging and unsafe. It is essential to note that cataract symptoms can vary among individuals. Some people may experience more pronounced symptoms, while others may have mild or intermittent symptoms. Regular eye examinations by an eye care professional are crucial for detecting cataracts, even in the absence of noticeable symptoms. In conclusion, recognizing the symptoms of cataracts is vital for early detection and appropriate management. Blurred vision, sensitivity to light, color distortion, and difficulty with night vision are common signs of cataracts. If individuals experience any of these symptoms, it is recommended to seek professional evaluation and discuss treatment options with an eye care specialist.",
        "image_url": "https://storage.googleapis.com/image_articles/Cataract%20Sypmtoms.jpg"
    },
    {
        "id": 3,
        "judul": "Causes of Cataracts",
        "deskripsi": "Cataracts can develop due to various factors, both controllable and uncontrollable. Understanding the causes of cataracts can help individuals take preventive measures and make informed decisions regarding their eye health.The primary factor contributing to cataract formation is age-related changes in the lens. As we age, the proteins in the lens can clump together, leading to clouding and opacity. This natural aging process is unavoidable and affects the majority of individuals to some degree as they get older.Exposure to ultraviolet (UV) radiation is another significant risk factor for cataract development. Prolonged and unprotected exposure to sunlight, especially to the harmful UV rays, can increase the risk of cataracts. It is crucial to wear UV-protective sunglasses and wide-brimmed hats when spending time outdoors to reduce UV exposure and protect the eyes.Certain medical conditions can also contribute to the development of cataracts. Individuals with diabetes are at an increased risk of developing cataracts due to the impact of high blood sugar levels on the lens. Other medical conditions, such as hypertension, obesity, and metabolic syndrome, have also been associated with a higher risk of cataracts. Lifestyle factors, such as smoking and excessive alcohol consumption, can increase the likelihood of developing cataracts. Smoking introduces harmful toxins into the body, including the eyes, which can accelerate the progression of cataracts. Excessive alcohol consumption can also contribute to cataract formation, potentially due to its impact on the lens and overall eye health. Injuries to the eye can lead to the development of cataracts. Trauma or injury that damages the lens can result in clouding and opacity over time. It is essential to protect the eyes from injury by wearing appropriate eye protection during activities that pose a risk of eye trauma. In conclusion, cataracts can be caused by various factors. While age-related changes in the lens are unavoidable, certain controllable factors such as UV radiation, medical conditions, lifestyle choices, and eye injuries can increase the risk of cataract development. By understanding these causes, individuals can take preventive measures and make informed decisions to maintain their eye health.",
        "image_url": "https://storage.googleapis.com/image_articles/Causes%20of%20cataract.jpg"
    },
    {
        "id": 4,
        "judul": "Treatment of Cataracts",
        "deskripsi": "When it comes to treating cataracts, several options are available to restore clear vision and improve quality of life for individuals affected by this condition. The most common and effective approach is cataract surgery. Cataract surgery involves the removal of the clouded lens and the insertion of an artificial intraocular lens (IOL) in its place. This surgical procedure is typically performed on an outpatient basis, meaning individuals can return home the same day. Cataract surgery is safe, well-established, and has a high success rate in improving vision. Before undergoing cataract surgery, a thorough preoperative evaluation is conducted to assess the individual's eye health and determine the most suitable IOL. Various types of IOLs are available, including monofocal, multifocal, and toric lenses. The selection of the IOL depends on factors such as the individual's visual needs, lifestyle, and presence of astigmatism. During the surgery, the clouded lens is carefully broken up and removed through a small incision in the eye. The artificial IOL is then inserted to replace the natural lens. The IOL is designed to provide improved focus and clarity, allowing individuals to see clearly at various distances, depending on the type of IOL chosen. Cataract surgery is generally a painless procedure performed under local anesthesia. After surgery, individuals may experience mild discomfort or irritation, but this usually subsides quickly. Vision improvement is often noticeable within a few days, with optimal results achieved within a few weeks. In less severe cases of cataracts, lifestyle adjustments and visual aids may offer temporary relief. These include optimizing lighting conditions at home, using anti-glare sunglasses to reduce sensitivity to light, and utilizing magnifying lenses or devices to assist with reading and other close-up tasks. In conclusion, cataract surgery is the primary treatment for cataracts and offers significant benefits in terms of vision restoration and quality of life improvement. With advancements in surgical techniques and the availability of various types of intraocular lenses, individuals with cataracts have the opportunity to regain clear vision and enjoy improved visual function.",
        "image_url": "https://storage.googleapis.com/image_articles/Treatment%20of%20cataract.jpg"
    },
    {
        "id": 5,
        "judul": "Prevention of Cataracts",
        "deskripsi": "While cataracts are primarily age-related and inevitable to some extent, certain measures can be taken to reduce the risk of developing cataracts and delay their progression. Implementing healthy lifestyle choices and practicing good eye care habits can contribute to the prevention of cataracts. One of the most important preventive measures is to protect the eyes from harmful ultraviolet (UV) radiation. UV rays from the sun can accelerate cataract formation, so it is crucial to wear sunglasses that provide 100% UV protection when outdoors. Additionally, using broad-brimmed hats or seeking shade during peak sunlight hours can further minimize UV exposure. Maintaining a healthy diet rich in antioxidants can also play a role in cataract prevention. Consuming a variety of fruits and vegetables, particularly those high in vitamins C and E, as well as foods containing lutein and zeaxanthin, can help protect the lens from oxidative damage. Examples of such foods include citrus fruits, berries, leafy greens, nuts, and seeds. Quitting smoking or avoiding tobacco use is another vital step in cataract prevention. Smoking has been strongly linked to the development and progression of cataracts. The harmful chemicals in tobacco smoke can cause oxidative stress and damage to the lens, increasing the risk of cataract formation. Quitting smoking can significantly lower this risk. Regular eye examinations are essential for early detection and timely management of eye conditions, including cataracts. Comprehensive eye exams allow eye care professionals to monitor the health of the eyes, detect any signs of cataracts, and provide appropriate guidance or treatment options. Early intervention can help slow down the progression of cataracts and preserve vision for longer. Maintaining overall health through regular exercise and managing chronic conditions such as diabetes and hypertension can also contribute to cataract prevention. By keeping these conditions under control, the risk of developing cataracts may be reduced. In conclusion, while cataracts are mainly age-related, preventive measures can be taken to reduce the risk and delay their onset. Protecting the eyes from UV radiation, maintaining a healthy diet, quitting smoking, regular eye examinations, and managing chronic conditions are key strategies in cataract prevention. By adopting these practices, individuals can promote long-term eye health and preserve clear vision.",
        "image_url": "https://storage.googleapis.com/image_articles/Prevention%20of%20cataract.jpg"
    },
    {
        "id": 6,
        "judul": "Impact of Cataracts",
        "deskripsi": "Cataracts can significantly impact an individual's vision and daily life, causing various challenges and limitations. Understanding the effects of cataracts is essential for individuals and their loved ones to seek appropriate treatment and support. One of the primary effects of cataracts is a decline in visual acuity. As the lens becomes cloudy, vision becomes increasingly blurry and hazy. This can make it difficult to perform daily tasks that require clear vision, such as reading, driving, and recognizing faces. Reduced visual acuity can also affect mobility and increase the risk of accidents or falls. Cataracts can also lead to increased sensitivity to light and glare. Bright lights, such as sunlight or artificial lighting, may cause discomfort and difficulty in visually adapting to different lighting conditions. This can make it challenging to be outdoors during the day or in well-lit environments, impacting social activities and overall quality of life. Color perception may be affected by cataracts. Colors may appear faded, dull, or yellowish due to the opacity of the lens. This can influence the ability to appreciate and distinguish between different colors, making activities such as selecting clothing or enjoying vibrant scenery less enjoyable. Night vision can be significantly impaired by cataracts. Dimly lit environments pose challenges for individuals with cataracts, as they may struggle to see clearly in low-light conditions. This can affect activities such as driving at night, navigating in dark areas, or participating in nighttime events. The impact of cataracts extends beyond vision alone. It can affect emotional well-being and overall quality of life. Frustration, anxiety, and a sense of isolation can arise from the limitations imposed by cataracts. Tasks that were once effortless may become arduous, leading to a loss of independence and a decreased engagement in social and recreational activities. Fortunately, cataract surgery offers a solution to mitigate the impacts of cataracts. By removing the cloudy lens and replacing it with an artificial intraocular lens, vision can be restored, and the limitations imposed by cataracts can be alleviated. Cataract surgery not only improves visual acuity but also enhances quality of life, allowing individuals to regain independence and actively participate in daily activities. In conclusion, cataracts have a profound impact on vision and daily life. Reduced visual acuity, sensitivity to light and glare, altered color perception, impaired night vision, and emotional effects can significantly affect an individual's well-being. However, with the availability of cataract surgery, individuals can regain clear vision and overcome the challenges imposed by cataracts, enabling them to lead fulfilling and active lives..",
        "image_url": "https://storage.googleapis.com/image_articles/impact%20of%20cataract.jpg"
    }
]

@app.route('/articles', methods=['POST'])
def store_articles():
    articles_data = request.json
    for article in articles_data:
        title = article.get('judul')
        content = article.get('deskripsi')
        image_url = article.get('image_url')
        articles.append({'judul': title, 'deskripsi': content, 'image_url': image_url})

    return jsonify({'message': 'Articles stored successfully'})

@app.route('/articles', methods=['GET'])
def get_articles():
    return jsonify({'articles': articles})

@app.route('/articles/<int:id>', methods=['GET'])
def get_article_by_id(id):
    for article in articles:
        if article['id'] == id:
            return jsonify(article)
    return jsonify({'message': 'Article not found'})

@app.route('/articles/<int:id>/image', methods=['GET'])
def get_article_image(id):
    for article in articles:
        if article['id'] == id:
            image_url = article.get('image_url')
            return jsonify({'image_url': image_url})
    return jsonify({'message': 'Article not found'})

if __name__ == '__main__':
    app.run()